name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  hetu_script: ^0.4.2+1
  hetu_std:
    git:
      url: https://github.com/hetu-community/hetu_std.git
      ref: main
  hetu_otp_util:
    git:
      url: https://github.com/hetu-community/hetu_otp_util.git
      ref: main
  hetu_spotube_plugin:
    git:
      url: https://github.com/KRTirtho/hetu_spotube_plugin.git
      ref: main
  get_it: ^9.0.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - packages/hetu_std/assets/bytecode/std.out
    - packages/hetu_spotube_plugin/assets/bytecode/spotube_plugin.out
    - assets/bytecode/plugin.out
